name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Test
        run: echo "No Tests Yet!"

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          echo ${GITHUB_WORKSPACE}
          cd app
          npm install -g eas-cli
          eas build -p android --profile preview --non-interactive