name: Build and Deploy
on:
  push:
    branches:
      - staging
permissions:
  contents: write
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: eas build -p android --profile preview --non-interactive